In [ ]:
%pip install -U sentence-transformers

In [ ]:
# https://huggingface.co/blog/matryoshka

In [ ]:
from sentence_transformers import SentenceTransformer
from sentence_transformers.util import cos_sim

matryoshka_dim = 64
model = SentenceTransformer("tomaarsen/mpnet-base-nli-matryoshka")

embeddings = model.encode([
    "Rachel is an amazing person.",
    "Maria is an incredible person.",
    "Nikhil is a fantastic person.",
    "Rachel is a wonderful person.",
    "Rachel hates carrots.",
    "Rachel hates food."
])

import numpy as np
print('Shape before truncation:', embeddings.shape)
print('Memory size before truncation: %.2f KB' % (embeddings.nbytes / 1024))

similarities = cos_sim(embeddings[0], embeddings[1:])
print(similarities)

embeddings = embeddings[:, :matryoshka_dim]
print('Shape after truncation:', embeddings.shape)
print('Memory size after truncation: %.2f KB' % (embeddings.nbytes / 1024))

similarities = cos_sim(embeddings[0], embeddings[1:])
print(similarities)


c:\Users\HillSeah\Documents\hill priv\vector-db-research\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\HillSeah\Documents\hill priv\vector-db-research\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\HillSeah\.cache\huggingface\hub\models--tomaarsen--mpnet-base-nli-matryoshka. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Develop

Shape before truncation: (6, 768)
Memory size before truncation: 18.00 KB
tensor([[0.7360, 0.4817, 0.9491, 0.2576, 0.3409]])
Shape after truncation: (6, 64)
Memory size after truncation: 1.50 KB
tensor([[0.7534, 0.5863, 0.9524, 0.2467, 0.2536]])


In [2]:
matryoshka_dim = 64
model = SentenceTransformer("tomaarsen/mpnet-base-nli-matryoshka", truncate_dim=matryoshka_dim)

In [3]:
embeddings = model.encode([
    "Rachel is an amazing person.",
    "Maria is an incredible person.",
    "Nikhil is a fantastic person.",
    "Rachel is a wonderful person.",
    "Rachel hates carrots.",
    "Rachel hates food."
])

In [4]:
print('Shape before truncation:', embeddings.shape)
print('Memory size before truncation: %.2f KB' % (embeddings.nbytes / 1024))

similarities = cos_sim(embeddings[0], embeddings[1:])
print(similarities)

embeddings = embeddings[:, :matryoshka_dim]
print('Shape after truncation:', embeddings.shape)
print('Memory size after truncation: %.2f KB' % (embeddings.nbytes / 1024))

similarities = cos_sim(embeddings[0], embeddings[1:])
print(similarities)

Shape before truncation: (6, 64)
Memory size before truncation: 1.50 KB
tensor([[0.7534, 0.5863, 0.9524, 0.2467, 0.2536]])
Shape after truncation: (6, 64)
Memory size after truncation: 1.50 KB
tensor([[0.7534, 0.5863, 0.9524, 0.2467, 0.2536]])
